AllCops:
  Includes:
    - Rakefile
    - config.ru
  Excludes:
    - db/**
    - config/**
    - script/**
    - bin/**
Documentation:
  Enabled: false
Metrics/LineLength:
  # Change the default 80 chars limit value
  Max: 120
