inherit_from: .rubocop_todo.yml

require: rubocop-rspec
AllCops:
  NewCops: enable
  Exclude:
    - bin/**
    - db/**
    - db/migrate/**
    - config/**
    - config/initializers/**
    - script/**
    - vendor/**/*
Layout/LineLength:
  # Change the default 80 chars limit value
  Max: 120
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  CountComments: false
  Max: 200
Metrics/ClassLength:
  Max: 200
Metrics/MethodLength:
  Max: 10
RSpec/MultipleExpectations:
  Max: 2
Style/Documentation:
  Enabled: false
Style/FormatStringToken:
  EnforcedStyle: template
Style/FrozenStringLiteralComment:
  Enabled: false
