addons:
  postgresql: 10.2
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - PGPORT=5432
dist: bionic
language: ruby
rvm:
  - 2.7.2
services:
  - postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
before_install:
  - sudo apt-get update
  - sudo apt-get install language-pack-es
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start 10
  - gem install bundler
script:
  - RAILS_ENV=test
  - bundle install
  - bundle exec rails db:create
  - bundle exec rails db:reset db:setup
  - bin/rails db:migrate
  - bundle exec rake db:seed
  - bundle exec rspec
  - bundle exec rubocop
  - bundle exec brakeman -z
