addons:
  postgresql: 10.2
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5432
dist: trusty
language: ruby
rvm:
- 2.5.7
services:
- postgresql
before_script:
- cp config/database.yml.travis config/database.yml
- sudo /etc/init.d/postgresql stop
- sudo /etc/init.d/postgresql start
before_install:
- gem install bundler
script:
- RAILS_ENV=test
- bundle install
- bundle exec rails db:create
- bin/rails db:migrate
- bundle exec rake db:seed
- bundle exec rspec
- bundle exec rubocop
- bundle exec brakeman -z
