addons:
  postgresql: 10.2
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5432
dist: trusty
language: ruby
rvm:
- 2.4.0
services:
- postgresql
before_script:
- cp config/database.yml.travis config/database.yml
- sudo /etc/init.d/postgresql stop
- sudo /etc/init.d/postgresql start
script:
- RAILS_ENV=test
- bundle install
- bundle exec rails db:create
- bin/rails db:migrate
- bundle exec rake db:seed
- bundle exec rspec
- bundle exec rubocop
- bundle exec brakeman -z
deploy:
  provider: heroku
  api_key:
    secure: 2JF9MbKYGCCdrAYtlWMzSZ1OJNTpOrvAnqbydUfKg9dnMaQBrb9OYtbT58UXKZolIIqhfk0wcC+0etxUGxMChBHF5sfiv7RVCcn6yq6UcDtUpSAgcnlGzI4nSDN3Kx6l/1y78MoY/i2Xxw2+8B5cmdZWmKu89FfBrTw0DYwgK+QmAZA1JteCvXH4UoXqor7H1IHPkAJdI1zATtU2aOIzj88Vfsyn8LSQIOWB1Boll9oojDrKm9df7I6t+oOr2jjpYNTZZ8EkrzqAuV1/qcFNqtEcyrmNhx8utJ83PQu3oVcZ1mXoc0l+HqIf+8AwSYxBz+y7V9G1Fziz7t2FbAwh9sjD4gd0Amx6mXIEAzuVBiOCthd6IoQwQnHMXJ4vJ7XypQfvuqvLQJ7v1dtBmy/uPU5r43U9ZXQIjlFZD2suKpBrs8OqllE+ZX45zSMMlAxlXCsQhHc64dxQLr3GpuxpVrOxOiuE+BpO7jYkGEJV0Iptd9dMDsLpGypqrpDi0XO7vt3Y4YyKE71CM3jEl+Ss4II/Aeaa0DFhRg6BlX9iTA8btXE2YT4aEKqqDDSHzBUhRTKm9vcBq2eBkqTR2b4iaA+v/LNgjz8+LNrStwOY7PUpeFkb15BPPiy/KeKlswUSUQcWl37VQYXYGptpeJH+5DJto4G/mVCoOkH81xKkIQs=
  app: dry-chamber-53826
  on:
    repo: isabel22/adopciones
